---
# Linux base role entrypoint

- name: Manage local groups
  ansible.builtin.import_tasks: groups.yaml

- name: Manage local users
  ansible.builtin.import_tasks: users.yaml

- name: Manage SSH access
  ansible.builtin.import_tasks: ssh.yaml

