---
# Manage SSH authorized keys
- name: Configure SSH authorized keys for users
  ansible.builtin.authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
    state: present
  loop: "{{ linux_users | subelements('ssh_keys', skip_missing=True) }}"

